/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package docstripper;

import java.io.IOException;
import java.util.Optional;

import org.apache.pdfbox.Loader;
import org.apache.pdfbox.pdmodel.PDDocumentInformation;
import org.apache.pdfbox.pdmodel.common.PDMetadata;

public class App {
    public static void main(String[] args) throws IOException {
        var srcFile = DialogUtils.chooseFile()
            .orElseThrow(() -> new IllegalArgumentException("No file chosen"));
        var pdf = Loader.loadPDF(srcFile);
        var docFYI = Optional.ofNullable(pdf.getDocumentInformation())
            .map(PDDocumentInformation::getCOSObject)
            .map(COSUtils::getFYI);
        var metadataFYI = Optional.ofNullable(pdf.getDocumentCatalog().getMetadata())
            .map(PDMetadata::getCOSObject)
            .map(COSUtils::getFYI);

        var fullMetadataFYI =
            docFYI.orElse("\nno document info") +
            metadataFYI.orElse("\nno xmp metadata");

        if (!DialogUtils.confirm(fullMetadataFYI))
            System.exit(0);

        var dstFile = DialogUtils.chooseNewFile()
            .orElseThrow(() -> new IllegalArgumentException("No destination file chosen!"));

        pdf.setDocumentInformation(new PDDocumentInformation());
        pdf.getDocumentCatalog().setMetadata(new PDMetadata(pdf));
        pdf.save(dstFile);
        pdf.close();
    }
}
